{% set name = "cf-autotick-bot-test-package" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/cf-autotick-bot-test-package/archive/v{{ version }}.tar.gz
  sha256: a562590dc65d50f7615f8dc098522d7f1b0cc19553c7ec313119bdf637d9b4e5

build:
  number: 0
  skip: true  # [py != 313 or win or aarch64 or ppc64le or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  commands:
    - echo "works!"

about:
  home: https://github.com/regro/cf-scripts
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: testing feedstock for the regro-cf-autotick-bot

extra:
  recipe-maintainers:
    - conda-forge-daemon
