{% set name = "cf-autotick-bot-test-package" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/cf-autotick-bot-test-package/archive/v{{ version }}.tar.gz
  sha256: 94aeeb512a602f3350fa22dd612b2b364b2a55c0f7e90a690deff2b0413ae81f

build:
  number: 0
  skip: true  # [py != 313 or win or aarch64 or ppc64le or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  commands:
    - echo "works!"

about:
  home: https://github.com/regro/cf-scripts
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: testing feedstock for the regro-cf-autotick-bot

extra:
  recipe-maintainers:
    - conda-forge-daemon
