{% set name = "cf-autotick-bot-test-package" %}
{% set version = "0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/regro/cf-autotick-bot-test-package/archive/v{{ version }}.tar.gz
  sha256: 471ff9c5a8892a8da8c7060164d6d05de13dd208f371491a8e71162f068f14c0

build:
  number: 128
  skip: true  # [py != 313 or win or aarch64 or ppc64le or s390x]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  commands:
    - echo "works!"

about:
  home: https://github.com/regro/cf-scripts
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: testing feedstock for the regro-cf-autotick-bot

extra:
  recipe-maintainers:
    - conda-forge-blah