bot:
  automerge: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: 2
provider:
  linux_64: github_actions
  linux_aarch64: github_actions
  osx_64: azure
  osx_arm64: github_actions
  win_64: github_actions
build_platform:
  osx_arm64: osx_arm64
  linux_aarch64: linux_aarch64
upload_on_branch: main
